### ISSUE TITLE
How to begin?

### ISSUE THREAD

**Issue by alakoring** [kateinoigakukun/IBLinter#13]
I hope this isn’t snarky, but how am I supposed to use this? There is no brew command on my machine…

(Yes I am vaguely aware that there is a thing called brew but I just want to try your tool. I’ve been using IB for many years but am obviously not plugged into the open source community.)

I’d love to see a beginner-friendly intro.

**Comment by kateinoigakukun** [comment]
I've created PR for documentation.
https://github.com/kateinoigakukun/IBLinter/pull/14

Do you have any questions or advice for change?

**Comment by alakoring** [comment]
Thank you! Hard to know, since I don’t have brew. At least a link to what it is? (Best from my standpoint is just something I can download and run, without having to worry about a zillion dependencies and learn how to manage them. Is it actually possible  to just get a standalone project and run it?)
