### ISSUE TITLE
Error for custom class seems incorrect

### ISSUE THREAD

**Issue by alakoring** [kateinoigakukun/IBLinter#17]
My storyboard has been working just fine but IBLinter reports

```
Resources/Base.lproj/Main.storyboard::: error: custom class name 'MainMenuController' should be 'Main' 
Resources/Base.lproj/Main.storyboard::: error: custom class name 'GameScreenController' should be 'Main' 
Resources/Base.lproj/Main.storyboard::: error: custom class name 'InfoDialogController' should be 'Main' 
```

I assume it is suggesting the name of the file. I don’t understand why you can’t have multiple UIViewController subclasses in a storyboard.

**Comment by alakoring** [comment]
I guess I should read the documentation! But, `custom_class_name` seems like a bad default, and it makes no sense when there are multiple controllers.

**Comment by kateinoigakukun** [comment]
I forgot to consider multiple view controllers. 😱 
I'll change to ignore `custom_class_name` when there are multiple view controllers.
But in my opinion, `custom_class_name` should be default rule. Generally it is not recommended that file name and custom class name do not match.

**Comment by alakoring** [comment]
Fair enough. (I have a lot of  .xib files that don’t match the class, for good reasons, but they are views not view controllers.)

**Comment by alper** [comment]
Please change this, it is I think more the exception to have only one UIViewController per Storyboard than it is the rule.

**Comment by alakoring** [comment]
It now handles multiple view controllers (i.e. a storyboard with segues to view controllers within the same file). So my original report is handled, thanks!

I get errors for

`CocoaLumberjack-master/Framework/iOSLibStaticTest/Base.lproj/Main.storyboard::: error: custom class name 'ViewController' should be 'Main'`

which seems a bit aggressive — isn’t `Main.storyboard` a pretty common convention?
