### ISSUE TITLE
Use Codable

### ISSUE THREAD

**Issue by kateinoigakukun** [kateinoigakukun/IBLinter#26]

**Comment by SD10** [comment]
Did you have any thoughts on how to achieve this? 

I tried converting the XML to JSON to use Codable but its too much trouble to create lossless or nicely formatted JSON. I'm trying to create a framework very similar to `IBLinterCore`.

**Comment by kateinoigakukun** [comment]
@SD10 Now, `IBLinterCore` is decoded by string literal key which is not safe way ☠️. For this reason, I would like to decode xml by `CodingKeys` which is generated automatically.
Your idea that converting XML to JSON looks toooo much trouble because of difference of structure between XML and JSON (ex. XML has attributes).
I tried to implement `XMLDecoder` as `Decoder` protocol but it is unable to extract attribute for `Decoder` protocol. So I would like to implement original `XMLDecoder` which doesn't conformed on `Decoder` protocol and use CodingKeys for type safe decode.

After a while, I'll create pull request for this implementation 👍

**Comment by SD10** [comment]
> Your idea that converting XML to JSON looks toooo much trouble because of difference of structure between XML and JSON (ex. XML has attributes).

You're right 😂 

@kateinoigakukun Don't worry, I understand what you mean. I spent many days trying to turn the XML into Swift data models so I've run into a lot of the same problems you have had to deal with.

`CodingKeys` is a good idea. Even a simple namespace with static properties would do well.

**Comment by SD10** [comment]
@kateinoigakukun If you want I can look into using `CodingKeys` for a safer API?

**Comment by kateinoigakukun** [comment]
@SD10 I'm implementing `decoder` now in this branch https://github.com/kateinoigakukun/IBLinter/tree/use_codingkeys

**Comment by SD10** [comment]
@kateinoigakukun Looking great!
